# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

C:\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is depr

In [3]:
tf.__version__

'1.14.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


### Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [15]:
print(X)

[[ 0.57873591 -0.57873591  0.99720391 ...  0.64609167  0.97024255
   0.02188649]
 [ 0.57873591 -0.57873591 -1.00280393 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.57873591 -0.57873591  0.99720391 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.57873591 -0.57873591  0.99720391 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.72790383  1.72790383 -1.00280393 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.57873591 -0.57873591  0.99720391 ...  0.64609167 -1.03067011
  -1.07636976]]


### Splitting the dataset into the Training set and Test set

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

## Part 2 - Building the ANN

### Initializing the ANN

In [61]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [62]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [63]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [64]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [65]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [66]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 0s 53us/sample - loss: 0.6338 - acc: 0.6801
Epoch 2/100
8000/8000 [==============================] - 0s 34us/sample - loss: 0.4612 - acc: 0.8071
Epoch 3/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4352 - acc: 0.8140
Epoch 4/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4261 - acc: 0.8198
Epoch 5/100
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4209 - acc: 0.8232
Epoch 6/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4174 - acc: 0.8246
Epoch 7/100
8000/8000 [==============================] - 0s 31us/sample - loss: 0.4145 - acc: 0.8250
Epoch 8/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4121 - acc: 0.8257
Epoch 9/100
8000/8000 [==============================] - 0s 32us/sample - loss: 0.4101 - acc: 0.8279
Epoch 10/100
8000/8000 [==============================] - 0s 29us/sample - loss: 0.4082 - a

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [67]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [68]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1509   86]
 [ 186  219]]
