In [31]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [3]:
X=dataset.iloc[:, 3:-1].values
y=dataset.iloc[:, -1].values

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [5]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [39]:
print(X)

[[ 1.          0.          0.57873591 ...  0.64609167  0.97024255
   0.02188649]
 [ 1.          0.          0.57873591 ... -1.54776799  0.97024255
   0.21653375]
 [ 1.          0.          0.57873591 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 1.          0.          0.57873591 ... -1.54776799  0.97024255
  -1.00864308]
 [ 0.          1.         -1.72790383 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 1.          0.          0.57873591 ...  0.64609167 -1.03067011
  -1.07636976]]


In [41]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X=sc.fit_transform(X)
X

array([[ 0.57873591, -0.57873591,  0.57873591, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 0.57873591, -0.57873591,  0.57873591, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.57873591, -0.57873591,  0.57873591, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.57873591, -0.57873591,  0.57873591, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.72790383,  1.72790383, -1.72790383, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.57873591, -0.57873591,  0.57873591, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [42]:
from sklearn.model_selection import train_test_split 
X_train, X_test,y_train,y_test= train_test_split(X, y, test_size=0.2, random_state=0)

In [43]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [44]:
# Building ANN

In [45]:
import keras
from keras.models import Sequential
from keras.layers import Dense   #dense basically use take random wight

In [46]:
classification=Sequential()

In [47]:
# Adding the input layer and the first hidden layer

In [48]:
#parameter tuning helps how much parameter should take

In [ ]:
'''when two binary in output like o and 1 then only one output take 
Now input is 11 and output is 1 so 11+1/2= 6 hidden layer'''
# output_dim=number of node you add in hiddden layer 
# input_dimits the dependent variable and just in first time

In [49]:
classification.add(Dense(output_dim=6, init='uniform', activation='relu'))       #unifom helps to iniatialize wight with uniform ditribution
# relu is define is activation function because relu work better in hidden layer and sigmoid in output layer

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [23]:
# see how to add second hidden layer

In [50]:
classification.add(Dense(output_dim=6, init='uniform', activation='relu'))

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [51]:
# outPut_layer how to add this

In [52]:
classification.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))    #outpur_dim=1 because output is only 1 funtion

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [127]:
'''If you have more than two parameter then you have to change two thing here those are
output_dense= be set as number of classes (input 3 if we have 3 variable) and change activation function like softmax'''

'If you have more than two parameter then you have to change two thing here those are\noutput_dense= be set as number of classes (input 3 if we have 3 variable) and change activation function like softmax'

In [53]:
# Compilee ANN(Artificial neural network)

In [54]:
classification.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# optimizer= to find the algorithm to find the optimum set of weight(best weight) 
#loss function define the predict and output difference if three then it will be categorical_crosentropy
#accuracy criteria to evaluate model after weight yodate algoeithm choose to model performance update

In [ ]:
''' Read how loss funtion could change'''

In [130]:
#Fitting the ANN to Training set

In [55]:
classification.fit(X_train, y_train, batch_size=32, epochs=100)
# setp_size= Number of observation work together when update weight
# epoch= After complte whole network 1 then ! epoch complete


Epoch 1/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.5615 - accuracy: 0.7949
Epoch 2/100
8000/8000 [==============================] - 0s 30us/step - loss: 0.4435 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 29us/step - loss: 0.4350 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 29us/step - loss: 0.4310 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 0s 28us/step - loss: 0.4280 - accuracy: 0.7985
Epoch 6/100
8000/8000 [==============================] - 0s 31us/step - loss: 0.4253 - accuracy: 0.8174
Epoch 7/100
8000/8000 [==============================] - 0s 29us/step - loss: 0.4228 - accuracy: 0.8204
Epoch 8/100
8000/8000 [==============================] - 0s 29us/step - loss: 0.4203 - accuracy: 0.8241
Epoch 9/100
8000/8000 [==============================] - 0s 28us/step - loss: 0.4182 - accuracy: 0.8265
Epoch 10/100
8000/8000 [==============================] - 0s 3

In [56]:
#### Predicting the Test set results

In [57]:
y_pred = classification.predict(X_test)   # Here we nee the prediction not probabilities
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [58]:
### Making the Confusion Matrix

In [59]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1503   92]
 [ 190  215]]
